# Generated by Django 4.2.6 on 2024-03-05 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_write', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='excerpt',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
