# Generated by Django 4.2.6 on 2024-03-05 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_write', '0002_alter_articles_excerpt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='excerpt',
            field=models.CharField(max_length=70, null=True),
        ),
    ]
