# Generated by Django 4.2.6 on 2024-03-05 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_write', '0004_alter_articles_excerpt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='excerpt',
            field=models.CharField(max_length=170, null=True),
        ),
        migrations.AlterField(
            model_name='articles',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
