# Generated by Django 4.2.6 on 2024-03-10 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_write', '0005_alter_articles_excerpt_alter_articles_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Biography',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ContentBiography', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Biography',
            },
        ),
    ]
