# Generated by Django 4.2.6 on 2024-03-11 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_write', '0008_clicklog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verifieduser',
            name='user',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
