# Generated by Django 4.2.6 on 2024-03-11 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_write', '0009_alter_verifieduser_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clicklog',
            old_name='click_type',
            new_name='click_by_type',
        ),
    ]
