# Generated by Django 5.0.1 on 2024-03-24 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_write', '0010_rename_click_type_clicklog_click_by_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clicklog',
            name='ip_address',
            field=models.CharField(max_length=50),
        ),
    ]
