# Generated by Django 5.0.6 on 2025-03-30 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_write', '0011_alter_clicklog_ip_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='excerpt',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
